server:
  port: 9002
  servlet:
    context-path: /analysis
spring:
  application:
    name: analysis-microservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/log_manage?useUnicode=true&characterEncoding=utf-8&&useSSL=false&&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1qaz2WSX!@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true